### ISSUE TITLE
Кросс-проверка

### ISSUE THREAD

**Issue by yaroslav-patrikeev** [TecHeReTiC3141/SHRI_React_HW#3]
Привет!

1. Создан github-репозиторий, в нём есть README, gitignore, установлены все необходимые зависимости. **5 / 5**
2. Проект запускается. **5/5**
3. По верстке в целом ок, но есть значительные отхождения от макета. **0 / 5**
Рекомендации:
Классно было бы, если бы сделал ui-компоненты кроме селекта для кнопки (так они были бы одинаковые), поисковой строки, инпутов и рейтинга. В идеале для селекта бы сделать появление с увеличением max-width.
Отхождения от макета:
Бросилось в глаза: кнопка "Войти" (убрать border). Нет hover состояния у кнопок, инпутов. Есть проблемы с отступами в карточках фильмов, авторизации, у селекторов. Нет реализации наведения, клика у большинства инпутов, кнопок. Не появляется иконка очистки поисковой строки. Кнопки в карусели не круглые, разные иконки стрелок на кнопках со стрелками в пагинации и в карусели. Рейтинг на главной странице не работает
Крутые фичи:
Круто, что анимировал лоадер. У всех страниц есть title. Реализована большая часть верстки.
4. Шапка позиционируется липко **2 / 2**
5. Для реализации модального окна используется портал **3 / 3**
6. После успешной авторизации кнопка «Войти» меняется на заглушку иконки пользователя и кнопку «Выйти» **2 / 2**
7. Сохраняем авторизационный токен из ответа ручки бэка (например, в localStorage) — **4 / 4**
8. В идеале, работать с токеном через thunk (где-то в мидлваре) — **3 / 3**
9. По клику на кнопку «Выйти» удаляем токен и снимает авторизацию — **2 / 2.**
10. При инициализации приложения проверяем авторизационный токен — **2 / 2.**
11. Поиск происходит во время ввода пользователем символов. Дёргаем ручку /search — **4 / 4**
12. Реализованы фильтры с dropdown — **4 / 4**
13. Сохранять фильтры в query-params —  **3 / 3** (у тебя сохраняется даже поисковая строка и все корректно удаляется при необходимости 👍)
15. Реализован список фильмов с пагинацией —  **3 / 3** (при применении фильтров номер странички сбрасывается 👍)
16. Реализована работа с получением данных **7 / 7**
17. Есть запрос за получением оценки для фильма — **3 / 3**
18. Если пользователь авторизован, даём возможность поставить оценку — запрос мутации — **3 / 3**
19. После выставления оценки обновляем кеш запроса /movie — **4 / 4**
20. Реализовать единообразную обработку ошибок для запросов — **2 / 2**
21. Реализовать единообразную обработку ошибок для запросов — **0 / 2**
22. Реализован лоадер — **2 / 2**
23. Используем debounce для поиска фильма и выставления оценки — **4 / 4**
24. Используется rtk и rtk-query — **4 / 4**
25. Данные корректно разбиты на модули (пример — авторизация, searchParams из фильтров) — **2 / 2**
26. Селекторы написаны оптимально (нет кучи дублирования) — **2 / 2** (я не увидел каких-то серьезных проблем, может плохо смотрел. единственное, я бы доставал селектор фильтра и деструктуризировал бы его, а не вызывал useAppSelector для каждого поля)

По первой работе от себя подсвечу несколько моментов.
Круто, что используешь алиасы.
Обрати внимание, что если сервер не запущен, приходит ошибка "Error: [object Object]".
Я бы советовал избавиться от console.log в проекте. Можно вынести API_URL в переменную сборщика или хотя бы захардкодить в отдельном файле (если бы вдруг я решил тестировать на своем сервере с другим портом, все бы сломалось).
Так же советую чуть подробнее разобраться с FSD. Удивило содержимое папки api в shared, ожидал увидеть там запросы rtk query. Еще больше удивил header в сущностях)) Конфигурацию store я бы перенес в app, там где ты его и используешь, в Layout можно тоже оборачивать в app. И напоследок поправить ошибки ts иначе в нем не было смысла.

27. Реализована миграция с использованием SSR — **14 / 14**
28. Для картинок используется Image некста. Скрины фильма, которые вне вьюпорта грузятся лениво — **2 / 2**
29. Страница фильма реализована с помощью Dynamic Routes — **4 / 4**

Тут меня смутили два скролла на главной странице и то, что ты в стор оборачиваешь в двух местах + все светится красным)

Работа достойная! Я насчитал **93 / 100**. Получается снял за верстку и за единообразную обработку ошибок. Селекторы не показались мне чудовищными. Если будут вопросы/возражения пиши в тг @gfopfm

**Comment by TecHeReTiC3141** [comment]
Большое спасибо за подробное и справедливое ревью, приму к сведению, особенно в плане FSD. Это мой первый проект на этой архитектуре (или ее подобии), основывается на 2 рандомных видео с ютуба, так что явно мне следует лучше разобраться. В плане селекторов в фильтре так и сделал в последнем коммите
